#ifndef __SIMPL_H__
#define __SIMPL_H__

#include <kiml/kiml.h>

typedef enum SIMPLCOMPILEERRORCODES
{
	SCE_NONE,
	SCE_DUPLICATE_SYMBOL,
	SCE_UNDECLARED_SYMBOL,
	SCE_TYPE_MISMATCHED,
	SCE_INCONSISTENT_ARG_COUNT,
	SCE_DECLARE_ONLY,
	SCE_ASSIGN_OR_FUNC_CALL_ONLY,
	SCE_ASSIGN_WRONG_LHS,
	SCE_CONST_NOT_CONST,
} SIMPLCOMPILEERRORCODES;

typedef struct SIMPLCOMPILEERRORINFO
{
	SIMPLCOMPILEERRORCODES code;
	KIMLUINT compileUnitIndex;
	KIMLUINT line;
} SIMPLCOMPILEERRORINFO;

#endif//__SIMPL_H__
